---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: first-deployment
spec:
  replicas: 4
  selector:
    matchLabels:
      app: ola-app
  template:
    metadata:
      labels:
        app: ola-app
    spec:
      containers:
      - name: container1
        image: nginx:1.25
  minReadySeconds: 10
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1

