apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name : replicaset1
  labels:
    app: myapp
spec:
  replicas: 3
  selector:
    matchLabels:
      app: myapp
  template:
   metadata :
     labels:
       app: myapp
   spec:
     containers:
     - name: my-containers
       image : nginx:1.24
